[window]
padding = { x = 10, y = 10 }
opacity = 0.9
decorations = "None"

[font]
size = 18
normal = { family = "JetBrains Mono NF" }

[cursor]
style = { shape = "Beam", blinking = "On" }

# Default colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
