#!/bin/bash
#
# Install all configs and favorite programs
#
###########################################################################
# Programs
###########################################################################
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install neovim
brew install git
brew install stow
brew install ripgrep
brew install fzf

###########################################################################
# dotfiles
###########################################################################
stow --target=~ neovim
