#!/bin/bash
#
# Install apps and configs I really need to get things done
#
#

# By default, macs make accent popups when keys are held down instead of repeating, this turns that off
defaults write -g ApplePressAndHoldEnabled -bool false
###########################################################################
# Programs
###########################################################################
brew install stow
brew install ripgrep
brew install fzf
brew install neovim
brew install fish
brew tap wez/wezterm
brew install --cask wez/wezterm/wezterm

###########################################################################
# dotfiles
###########################################################################
stow fish
stow nvim
stow wezterm
