#!/bin/bash
#
# Install all configs and favorite programs
#
###########################################################################
# Programs
###########################################################################
# Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# brew install jesseduffield/lazygit/lazygit
brew intall neovim

###########################################################################
# dotfiles
###########################################################################
