#!/bin/bash
#
# Install all configs and favorite programs
#
###########################################################################
# Programs
###########################################################################
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install git
brew install stow
brew install ripgrep
brew install fzf
brew install neovim
brew cask install iterm2
brew install --cask temurin
brew install --cask intellij-idea

###########################################################################
# dotfiles
###########################################################################
stow nvim
