#!/bin/bash
#
# Install apps and configs I really need to get things done
#

###########################################################################
# Programs
###########################################################################
brew install stow
brew install ripgrep
brew install fzf
brew install neovim


###########################################################################
# dotfiles
###########################################################################
stow nvim
