#!/bin/bash
#
# Install apps and configs I really need to get things done
#

###########################################################################
# Programs
###########################################################################
brew install stow
brew install ripgrep
brew install fzf
brew install neovim
brew install fish
brew tap wez/wezterm
brew install --cask wez/wezterm/wezterm

###########################################################################
# dotfiles
###########################################################################
stow fish
stow nvim
stow wezterm
