# excludes = ["*.md", "*.gif"]

# Log paths that did not match any formatters at the specified log level
# Possible values are <debug|info|warn|error|fatal>
# Env $TREEFMT_ON_UNMATCHED
# on-unmatched = "info"

walk = "git"

[formatter.nix]
command = "nix"
options = ["fmt"]
includes = [ "*.nix" ]
excludes = []
