# syntax=docker/dockerfile:1
   
FROM alpine:3.17

copy packages.txt .
RUN apk update \
    && apk upgrade \
    && xargs apk add <packages.txt

WORKDIR /root
RUN git clone https://github.com/colbs255/dotfiles.git \
    && cd dotfiles \
    && stow nvim \
    && stow fish

CMD ["fish"]
