onboarding = false

[theme]
name = "tokyo-night"

[terminal]
default_shell = "fish"

[update]
version_check = false

[ui]
status_indicators = "symbols"

[keys]
prefix = "ctrl+space"

[worktrees]
directory = "~/.local/share/herdr/worktrees"

[experimental]
pane_history = false

[advanced]
scrollback_limit_bytes = 10000000
