onboarding = false

[theme]
name = "tokyo-night"

[terminal]
default_shell = "fish"

[update]
version_check = false

[ui]
status_indicators = "symbols"

[ui.toast]
delivery = "system"

[keys]
prefix = "ctrl+space"
next_agent = "prefix+n"
previous_agent = "prefix+p"
next_tab = "prefix+."
previous_tab = "prefix+,"
goto = "prefix+s"
settings = ""

[[keys.command]]
key = "prefix+d"
type = "popup"
command = "~/.config/herdr/scripts/spawn-agent.sh"
width = "80%"
height = "80%"

[worktrees]
directory = "~/.local/share/herdr/worktrees"

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
description = "lazygit"
width = "80%"
height = "80%"

[experimental]
pane_history = false

[advanced]
scrollback_limit_bytes = 10000000
