#!/usr/bin/env bash

choices="Lock
Logout
Shutdown
Reboot"
choice=$(fuzzel --dmenu <<< "$choices")

case $choice in
    "Lock")
        hyprlock
        ;;
    "Logout")
        hyprctl dispatch exit
        ;;
    "Shutdown")
        systemctl poweroff
        ;;
    "Reboot")
        systemctl reboot
        ;;
    *)
        ;;
esac
