name: validate configs

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate configs
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v35
    - name: Nix flake check
      run: nix flake check -L
