name: validate configs

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  validate-nix:
    runs-on: ubuntu-latest
    name: Validate nix configs
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    - name: Nix flake check
      run: nix flake check
    - name: Nix format
      run: nix fmt && git diff --exit-code
  validate-lua:
    runs-on: ubuntu-latest
    name: Lint lua files
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    - name: Stylua
      run: nix develop --command 'just lint-lua'
  validate-shell:
    runs-on: ubuntu-latest
    name: Lint shell files
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    - name: Shellcheck
      run: nix develop --command 'just lint-shell'
