name: validate configs

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  validate-nix:
    runs-on: ubuntu-latest
    name: Validate nix configs
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    - name: Nix flake check
      working-directory: ./config
      run: nix flake check
    - name: Nix format
      working-directory: ./config
      run: nix fmt && git diff --exit-code
  validate-lua:
    runs-on: ubuntu-latest
    name: Validate lua files
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: v0.20.0
        args: --check config/nvim
  validate-shell:
    runs-on: ubuntu-latest
    name: Validate shell scripts
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    - name: Shellcheck
      run: nix shell nixpkgs#fd nixpkgs#shellcheck --command bash -c 'shellcheck $(fd -e sh)'
